export const FETCH_SUMBERDANA = 'FETCH_SUMBERDANA';
export const FETCH_REALISASIPD = 'FETCH_REALISASIPD';
export const FETCH_REALISASI_DAU = 'FETCH_REALISASI_DAU';
export const FETCH_REALISASI_DAK = 'FETCH_REALISASI_DAK';
export const FETCH_REALISASI_OTSUS = 'FETCH_REALISASI_OTSUS';
export const FETCH_REALISASI_PAD = 'FETCH_REALISASI_PAD';
export const FETCH_REALISASI_DBH = 'FETCH_REALISASI_DBH';
export const FETCH_REALISASI_DID = 'FETCH_REALISASI_DID';